# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='filedata',
            field=models.FileField(blank=True, upload_to='Users/emodatt08/Documents/python/shoutout/uploads/'),
        ),
    ]
